# Generated by Django 6.0.2 on 2026-02-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
